title: "wai9"
url: "https://wai9.site"

collections:
    notes:
        output: true
        permalink: /:collection/:name/
    recipes:
        output: true
        permalink: /:collection/:name/

exclude:
    - deploy.sh
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/

theme: jekyll-theme-hacker
markdown: kramdown
