title: "markus' site"
permalink: /:year/:month/:day/:title/

collections:
    notes:
        output: true
        permalink: /:collection/:name/
    recipes:
        output: true
        permalink: /:collection/:name/

exclude:
    - CNAME
    - deploy.sh
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor/

theme: jekyll-theme-primer
